" Set nocompatible first since it's special
set nocompatible

" Colors
	set hlsearch
	if &diff | syntax off | else | syntax enable | endif

	set background=dark
	command ToggleBG if &bg == 'dark' | set bg=light | else | set bg=dark | endif
	nmap .. :ToggleBG<CR>

" Indentation
	filetype plugin indent on
	set autoindent
	set copyindent
	set preserveindent
	set nosmartindent

" Tabbing
	set noexpandtab
	set shiftwidth=8
	set nosmarttab
	set softtabstop=0
	set tabstop=8

" Mouse
	set mouse=a
	if has('mouse_sgr') | set ttymouse=sgr | end

" Misc options
	set noeol
	set ignorecase
	set smartcase
	set backspace=indent,eol,start
	set cmdheight=1
	set linebreak
	set linespace=0
	set modeline
	set modelines=5
	set nonumber
	set nopaste
	set pastetoggle=<F12>
	set restorescreen
	set ruler
	set showbreak=>
	set textwidth=0
	set undolevels=1000
	set wrap

" Set 'very magic' mode. See ':help magic'.
	" https://vim.fandom.com/wiki/Simplifying_regular_expressions_using_magic_and_no-magic
	nnoremap / /\v
	vnoremap / /\v
	cnoremap %s/ %smagic/
	cnoremap \>s/ \>smagic/
	nnoremap :g/ :g/\v
	nnoremap :g// :g//

" Remember cursor position (for most files)
	autocmd BufReadPost *
		\ if ["gitcommit", "hgcommit"]->index(&filetype) < 0
		\ && line("'\"") > 1 && line("'\"") <= line("$")
		\ 	| execute "normal! g'\""
		\ | endif

" Create parent directories
	" https://stackoverflow.com/questions/4292733/vim-creating-parent-directories-on-save
	function s:MkNonExDir(file, buf)
		if empty(getbufvar(a:buf, '&buftype')) && a:file!~#'\v^\w+\:\/'
			let dir=fnamemodify(a:file, ':h')
			if !isdirectory(dir)
				call mkdir(dir, 'p')
			endif
		endif
	endfunction
	augroup BWCCreateDir
		autocmd!
		autocmd BufWritePre * :call s:MkNonExDir(expand('<afile>'), +expand('<abuf>'))
	augroup END

" FileType specific settings
	autocmd FileType go setlocal textwidth=110
