# alacritty.toml
#
# Alacritty is typically launched with sway keybindings so see
# ~/.config/sway/config
#

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[font]
size = 12

[scrolling]
history = 100000

[window]
opacity = 0.9
