on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 2 * * 1-5"

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
 test-job:
    name: Test Job
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: PWD
        run: pwd
      - name: LS
        run: ls -alh
      - name: apt install sway
        run: sudo apt-get install -y sway
      - name: Check Sway
        run: WLR_BACKENDS=headless sway --validate --config .config/sway/config
      - name: ENV
        run: env | sort
